image: Visual Studio 2017

version: 1.0.{build}
configuration: Release
platform: Any CPU
skip_tags: true             # to prevent a endless build loop

before_build:
- cmd: nuget restore

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'

build:
  verbosity: minimal
  project: MouseTrap.sln

artifacts:
- path: MouseTrap\bin\*.exe

# deploy:
#   release: v$(appveyor_build_version)
#   # description: 'Release description'
#   provider: GitHub
#   auth_token:
#     secure: zYHtyBs13JvlzMOq5tFTt6qCGLGBKEBNGK0Ho/c9ZsuknYU5M62uYMymS66cxgDH
#   # artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
#   draft: false
#   prerelease: false
#   on:
#     branch: master                   # release from master branch only
#     # APPVEYOR_REPO_TAG: true          # deploy on tag push only
