image: Visual Studio 2019

branches:
  only:
    - master

version: 1.0.{build}
configuration: Release
platform: Any CPU
skip_tags: true             # to prevent a endless build loop

environment:
  choco_api_token:
    secure: Rym1kbOorVRtBplky8zDAaWiNA3MnD48MoL5SboGtQPXqVJZVXJrytFD0AtwVqID

before_build:
- cmd: nuget restore

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'

build:
  verbosity: minimal
  project: MouseTrap.sln

after_build:
- ps: .\build\Create-Artifacts.ps1 $env:appveyor_build_version

artifacts:
- path: MouseTrap\bin\*.zip
- path: MouseTrap\bin\*.nupkg

deploy:
- provider: GitHub
  release: v$(appveyor_build_version)-beta
  prerelease: true
  draft: false
  description: |
    MouseTrap is a portable application.
    Download the *.zip archive and extract it to some safe place (where you don't delete it by mistake)
    and double click mousetrap.exe to run it.

    Please download and install [**.NET 6 Runtime**](https://dotnet.microsoft.com/download/dotnet/current/runtime) if you have trouble running mousetrap
    _in most cases it will notify you with a simple message dialog if the runtime is missing_

    [Documentation + Help](https://github.com/r-Larch/MouseTrap/blob/master/README.md)

    ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) Please Note!!
    > The **MouseTrap.exe is not signed!** Because Code signing certificates cost a lot of money.
    So in case you get some "Windows protected your PC" warning, just hit "more infos" and then "Run anyway".
    Or download the Source Code and Build it on your own.
  auth_token:
    secure: zYHtyBs13JvlzMOq5tFTt6qCGLGBKEBNGK0Ho/c9ZsuknYU5M62uYMymS66cxgDH
  # artifact: /*\.exe/
  on:
    branch: master

after_deploy:
- ps: choco push $(Resolve-Path $env:appveyor_build_folder\MouseTrap\bin\*.nupkg).ToString() --source https://push.chocolatey.org/ --key $env:choco_api_token